version: '3.8'

services:

  mongo-db:
    container_name: mongo-db
    image: mongo:4.4.18
    restart: always
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_User}  # Root uživatel
      MONGO_INITDB_ROOT_PASSWORD: ${DB_Password}  # Root heslo
      MONGO_INITDB_DATABASE: sensor_database
    ports:
      - "50002:27017"
    networks:
      - internal-network
    healthcheck:  
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mongo-express:
    container_name: hydro-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_User}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_Password}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_User}:${DB_Password}@mongo-db:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_User}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_Password}
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
    external: false