version: '3.8'

services:

  backend:
    container_name: hydro-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo-db
    networks:
      - internal-network

  frontend:
    container_name: hydro-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    networks:
      - internal-network

  mongo-db:
    container_name: hydro-mongo
    image: mongo:latest
    restart: always
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_User}  # Root uživatel
      MONGO_INITDB_ROOT_PASSWORD: ${DB_Password}  # Root heslo
      MONGO_INITDB_DATABASE: hydroData
    ports:
      - "50002:27017"
    networks:
      - internal-network
    healthcheck:  
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mongo-express:
    container_name: hydro-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_User}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_Password}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_User}:${DB_Password}@hydro-mongo:27017/
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
    external: false